# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('stars', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
